import type { NextPage } from 'next';
import Head from 'next/head';
import { trpc } from '../utils';

const Home: NextPage = () => {
	const { data, isLoading } = trpc.useQuery(['siemka', { text: 'Vuko' }]);

	if (isLoading) return <div>Ładowanie...</div>;

	if (data) return <div>{data.greeting}</div>;

	return (
		<div className={''}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='h-screen w-screen flex flex-col justify-center items-center'>
				<div className='text-2xl text-center'>Który Pokemon jest okrąglejszy? </div>
				<div className='p-2' />
				<div className='border rounded p-8 flex justify-between max-w-2xl items-center'>
					<div className='w-16 h-16 bg-red-400'>Vuko</div>
					<div className='p-8'>Vs</div>
					<div className='w-16 h-16 bg-pink-400'>Kamil</div>
				</div>
			</div>
		</div>
	);
};

export default Home;
